#!/usr/bin/env node
// Assemble www/ for the iOS app from the repo root + capacitor/src.
//
// Cody's renderer.js stays the single source of truth: the note
// parser/serializer and the whole drawer lookup engine are EXTRACTED from it
// at build time (marker-based slices, loud failure on drift) rather than
// copied into this tree. lockin.html is copied and patched, never forked.
const fs = require('fs')
const path = require('path')
const vm = require('vm')
const { execFileSync } = require('child_process')

const CAP = path.join(__dirname, '..')
const ROOT = path.join(CAP, '..')
const SRC = path.join(CAP, 'src')
const WWW = path.join(CAP, 'www')

function fail(msg) { console.error('BUILD FAIL: ' + msg); process.exit(1) }

// ── slice renderer.js ──
const renderer = fs.readFileSync(path.join(ROOT, 'renderer.js'), 'utf8')

function slice(startMarker, endMarker) {
  const s = renderer.indexOf(startMarker)
  if (s === -1) fail(`marker not found: ${startMarker}`)
  const e = renderer.indexOf(endMarker, s)
  if (e === -1) fail(`end marker not found: ${endMarker}`)
  return renderer.slice(s, e)
}

const core = [
  '// GENERATED by capacitor/tools/build-www.js — do not edit.',
  '// Extracted from ../renderer.js so Cody\'s code stays the single source.',
  "const WRITE_DIR='write', PLAN_DIR='plan', LONGFORM_DIR='longform', PROJECTS_DIR='projects'",
  "let cmuDict=null, wn=null, bibleIndex=null, newTabMode='write'",
  slice('function looksLikeStaveNote(', 'let tabs'),
  slice('function getPhones(', 'function emptyTab('),
  slice('function emptyTab(', 'function ensureDirs('),
  `window.StaveCore = {
  setCmu(cache) { cmuDict = { _cache: cache, get: w => cache[w] } },
  setBible(idx) { bibleIndex = idx },
  hasCmu: () => !!cmuDict, hasBible: () => !!bibleIndex,
  bible: w => (bibleIndex ? (bibleIndex[w] || []) : []),
  getRhymeSignature, findRhymes, countSyllables, countLineSyllables,
  findWordWebMatches, getPaletteCategories, SONGS_WORDS,
  serializeTab, parseNote, emptyTab, getDirForMode, getColorForMode,
  newTaskId, tabHasContent, looksLikeStaveNote
}`
].join('\n\n')

// ── verify the extracted core actually works ──
const sandbox = { window: {}, console }
vm.runInNewContext(core, sandbox)
const C = sandbox.window.StaveCore
if (!C) fail('StaveCore did not initialize')
const syl = C.countSyllables('hallelujah')
if (syl !== 4) fail(`countSyllables sanity: hallelujah => ${syl}, want 4`)
const tab = C.emptyTab('write')
tab.title = 'Roundtrip'; tab.idea = 'line one\nline two'; tab.context = 'ctx'; tab.tags = ['a', 'b']
const parsed = C.parseNote(C.serializeTab(tab), 'write')
if (parsed.title !== 'Roundtrip' || parsed.idea.trim() !== 'line one\nline two' || parsed.tags.join(',') !== 'a,b')
  fail('serializeTab/parseNote roundtrip broke: ' + JSON.stringify(parsed))
console.log('extracted core: OK (syllables + roundtrip pass)')

// ── assemble www ──
fs.rmSync(WWW, { recursive: true, force: true })
fs.mkdirSync(WWW, { recursive: true })
fs.writeFileSync(path.join(WWW, 'stave-core.js'), core)

// lockin.html: inject viewport + shim before the first <script>, patches at the end
let lockin = fs.readFileSync(path.join(ROOT, 'lockin.html'), 'utf8')
if (!lockin.includes('<head>')) fail('lockin.html: no <head>')
lockin = lockin.replace('<head>',
  '<head>\n  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, viewport-fit=cover">')
if (!lockin.includes('</head>')) fail('lockin.html: no </head>')
// after the page's inline <style> so iOS overrides actually win
lockin = lockin.replace('</head>', '  <link rel="stylesheet" href="ios.css">\n</head>')
const firstScript = lockin.indexOf('<script>')
if (firstScript === -1) fail('lockin.html: no inline <script>')
lockin = lockin.slice(0, firstScript)
  + '<script src="stave-core.js"></script>\n  <script src="shim.js"></script>\n  '
  + lockin.slice(firstScript)
if (!lockin.includes('</body>')) fail('lockin.html: no </body>')
lockin = lockin.replace('</body>', '  <script src="lockin-ios-patch.js"></script>\n</body>')
fs.writeFileSync(path.join(WWW, 'lockin.html'), lockin)

// home page + shim + patches
fs.copyFileSync(path.join(SRC, 'home.html'), path.join(WWW, 'index.html'))
for (const f of ['home.js', 'shim.js', 'ios.css', 'lockin-ios-patch.js'])
  fs.copyFileSync(path.join(SRC, f), path.join(WWW, f))

// data files
fs.copyFileSync(path.join(ROOT, 'bible-index.json'), path.join(WWW, 'bible-index.json'))
execFileSync('node', [path.join(__dirname, 'dump-cmudict.js'), path.join(WWW, 'cmudict.json')], { stdio: 'inherit' })

const total = fs.readdirSync(WWW).reduce((s, f) => s + fs.statSync(path.join(WWW, f)).size, 0)
console.log(`www/ assembled: ${fs.readdirSync(WWW).length} files, ${(total / 1024 / 1024).toFixed(1)}MB`)
